[tools]
aws-sso = "latest"
awscli = "latest"
dotnet = "8"
go = "1.23.4"
java = "latest"
lua = "5.1"
node = "23.5.0"
python = "3.13.1"
ruby = "3.4.1"
rust = "latest"
terraform = "1.5.7"
usage = "latest"
